name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  tf-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run make tf-lint
        run: make tf-lint

  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tfsec
        uses: aquasecurity/setup-tfsec@v1

      - name: Run make tf-sec
        run: make tf-sec